// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQUEzA85yToCyu076cUZoot8hM9xhsyuo',
    appId: '1:169295692118:web:301ca4bbe5dfbba88656f7',
    messagingSenderId: '169295692118',
    projectId: 'quickcheck-frontend',
    authDomain: 'quickcheck-frontend.firebaseapp.com',
    storageBucket: 'quickcheck-frontend.appspot.com',
    measurementId: 'G-C35B9V4YCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbDQL2hync5DToGlY6X1EdQ9tn1TRXQBI',
    appId: '1:169295692118:android:cf53206b522c3d198656f7',
    messagingSenderId: '169295692118',
    projectId: 'quickcheck-frontend',
    storageBucket: 'quickcheck-frontend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4cIlP_TgG1SbPEbeSNXhaYOFxZkadk4M',
    appId: '1:169295692118:ios:44a7858329f10c7b8656f7',
    messagingSenderId: '169295692118',
    projectId: 'quickcheck-frontend',
    storageBucket: 'quickcheck-frontend.appspot.com',
    iosClientId: '169295692118-580rlhnpc8ur9hkank1u3kb36gm92hf5.apps.googleusercontent.com',
    iosBundleId: 'com.tonydoesathing.quickcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4cIlP_TgG1SbPEbeSNXhaYOFxZkadk4M',
    appId: '1:169295692118:ios:44a7858329f10c7b8656f7',
    messagingSenderId: '169295692118',
    projectId: 'quickcheck-frontend',
    storageBucket: 'quickcheck-frontend.appspot.com',
    iosClientId: '169295692118-580rlhnpc8ur9hkank1u3kb36gm92hf5.apps.googleusercontent.com',
    iosBundleId: 'com.tonydoesathing.quickcheck',
  );
}
