/// Flutter icons QuickCheckIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QuickCheckIcons
///      fonts:
///       - asset: fonts/QuickCheckIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class QuickCheckIcons {
  QuickCheckIcons._();

  static const _kFontFam = 'QuickCheckIcons';
  static const String? _kFontPkg = null;

  static const IconData one_rating_icon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two_rating_icon =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData four_rating_icon =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_rating_icon =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zero_rating_icon =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
